---

# 文件下载目录，非必改变量
downloads_dir: "{{ playbook_dir }}/downloads"

# 证书文件，非必改目录
via_cert_dir:   "{{ playbook_dir }}/config/via_cert"
carrier_cert_dir:   "{{ playbook_dir }}/config/carrier_cert"
admin_cert_dir:   "{{ playbook_dir }}/config/admin_cert"
scan_cert_dir:   "{{ playbook_dir }}/config/scan_cert"
storage_cert_dir:   "{{ playbook_dir }}/config/storage_cert"
compute_cert_dir:   "{{ playbook_dir }}/config/computer_cert"
data_cert_dir:   "{{ playbook_dir }}/config/data_cert" 

# 服务静态文件下载 url
download_url: "http://192.168.9.150/metis/"
consul_download_url: "https://releases.hashicorp.com/consul/1.10.4/consul_1.10.4_linux_amd64.zip"

# admin web 服务相关配置信息
admin_server_name: metis-admin.platon.network
admin_ssl_protocols: "TLSv1 TLSv1.1 TLSv1.2"
admin_ssl_ciphers: ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-GCM-SHA256:DHE-RSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-SHA384:ECDHE-RSA-AES128-SHA256:ECDHE-RSA-AES256-SHA:ECDHE-RSA-AES128-SHA:DHE-RSA-AES256-SHA256:DHE-RSA-AES128-SHA256:DHE-RSA-AES256-SHA:DHE-RSA-AES128-SHA:ECDHE-RSA-DES-CBC3-SHA:EDH-RSA-DES-CBC3-SHA:AES256-GCM-SHA384:AES128-GCM-SHA256:AES256-SHA256:AES128-SHA256:AES256-SHA:AES128-SHA:DES-CBC3-SHA:HIGH:!aNULL:!eNULL:!EXPORT:!DES:!MD5:!PSK:!RC4

# mysql 相关用户名密码
mysql_root_password: jatel
amin_user: metis_admin
admin_password: admin_123456
storage_user: metis_storage
storage_password: storage_123456

###############################################
# 端口号根据自己的部署情况进行设置
# consul 端口号
consul_server_port: [8200, 8201, 8202]
consul_serf_lan_port: [8300, 8301, 8302]
consul_serf_wan_port: [8400, 8401, 8402]
consul_http_port: [8500, 8501, 8502]
consul_dns_port: [8600, 8601, 8602]

# data 端口号
data_port: 10037

# compute 端口号
compute_port: 10038

# via 服务端口号
via_port: 10031

# carrier 端口号
carrier_pprof_port: 10032
carrier_rpc_port: 10033
carrier_grpc_gateway_port: 10034
bootstrap_node: []
carrier_p2p_udp_port: 10035
carrier_p2p_tcp_port: 10036

# admin 端口号
admin_web_port: 9090

# storage 端口号
storage_port: 10039

# scan 端口号
scan_web_port: 9001
###############################################

# consul agent 信息
consul_host: "{{ groups['consul'][0] }}"
consul_port: "{{ consul_http_port[0] }}"

