---
# 在各个节点安装相应服务

# deploy metis cluster

- name: deploying via 
  hosts: via
  tags:
    - via_servers
  roles:
    - via_deploy

- name: deploying carrier
  hosts: carrier
  tags:
    - carrier_servers
  roles:
    - carrier_deploy

- name: deploying admin
  hosts: admin
  tags:
    - admin_servers
  roles:
    - admin_deploy

- name: deploying data
  hosts: data_servers
  tags:
    - data
  roles:
    - data_deploy

- name: deploying compute
  hosts: compute_servers
  tags:
    - compute
  roles:
    - compute_deploy

- name: deploying consul
  hosts: consul_servers
  tags:
    - consul
  roles:
    - consul_deploy

- name: deploying storage
  hosts: storage_servers
  tags:
    - storage
  roles:
    - storage_deploy

# - name: deploying scan
#   hosts: scan
#   tags:
#     - scan
#   roles:
#     - scan_deploy