---
# 在各个节点安装相应服务

# deploy metis cluster

# - name: deploying via 
#   hosts: via
#   tags:
#     - via
#   roles:
#     - via_deploy

# - name: deploying carrier
#   hosts: carrier
#   tags:
#     - carrier
#   roles:
#     - carrier_deploy

# - name: deploying admin
#   hosts: admin
#   tags:
#     - admin
#   roles:
#     - admin_deploy

# - name: deploying data
#   hosts: data
#   tags:
#     - data
#   roles:
#     - data_deploy

# - name: deploying compute
#   hosts: compute
#   tags:
#     - compute
#   roles:
#     - compute_deploy

# - name: deploying consul
#   hosts: consul
#   tags:
#     - consul
#   roles:
#     - consul_deploy

- name: deploying storage
  hosts: storage
  tags:
    - storage
  roles:
    - storage_deploy

# - name: deploying scan
#   hosts: scan
#   tags:
#     - scan
#   roles:
#     - scan_deploy