---

# 停止所有服务

- hosts: via
  tags:
    - via
  tasks:
    - name: stop via
      shell: ps -ef | grep "{{ deploy_dir }}/via/via -cnf {{ deploy_dir }}/via/conf/via.yml" | grep -v "grep" | awk -v FS=" " '{print $2}' | xargs kill -s TERM

    - name: wait until the via_port is down
      wait_for:
        host: "{{ ansible_host }}"
        port: "{{ via_port }}"
        state: stopped
        msg: "the pump port {{ via_port }} is not down"


# - hosts: carrier
#   tags:
#     - carrier
#   tasks:
#     - name: stop carrier
#       shell: ps -ef | grep {{ deploy_dir }}/carrier/carrier | awk -v FS=" " '{print $1,$2}' | kill -2

#     - name: wait until the carrier_rpc_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ carrier_rpc_port }}"
#         state: stopped
#         msg: "the pump port {{ carrier_rpc_port }} is not down"

# - hosts: admin
#   tags:
#     - admin
#   tasks:
#     - name: stop admin
#       shell: ps -ef | grep "java -jar {{ deploy_dir }}/admin/admin.jar" | awk -v FS=" " '{print $1,$2}' | kill -9

#     - name: wait until the admin_web_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ admin_web_port }}"
#         state: stopped
#         msg: "the pump port {{ admin_web_port }} is not down"

# - hosts: data
#   tags:
#     - data
#   tasks:
#     - name: stop data
#       shell: "nohup {{ deploy_dir }}/data/start_data_svc.sh {{ deploy_dir }}/data/conf/data.yml &"

#     - name: wait until the data_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ data_port }}"
#         state: stopped
#         msg: "the pump port {{ data_port }} is not down"

# - hosts: compute
#   tags:
#     - compute
#   tasks:
#     - name: stop compute
#       shell: "nohup {{ deploy_dir }}/compute/start_compute_svc.sh {{ deploy_dir }}/compute/conf/compute.yml &"

#     - name: wait until the compute_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ compute_port }}"
#         state: stopped
#         msg: "the pump port {{ compute_port }} is not down"

# # - name: stop consul
# #   hosts: consul
# #   tags:
# #     - consul
# #   tasks:
# #     shell: "nohup {{ deploy_dir }}/compute/start_compute_svc.sh {{ deploy_dir }}/compute/conf/compute.yml &"

# - hosts: storage
#   tags:
#     - storage
#   tasks:
#     - name: stop storage
#       shell: ps -ef | grep "java -jar {{ deploy_dir }}/storage/storage.jar" | awk -v FS=" " '{print $1,$2}' | kill -9

#     - name: wait until the storage_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ storage_port }}"
#         state: stopped
#         msg: "the pump port {{ storage_port }} is not down"

# - hosts: scan
#   tags:
#     - scan
#   tasks:
#     - name: start scan
#       shell: ps -ef | grep "java -jar {{ deploy_dir }}/scan/scan.jar" | awk -v FS=" " '{print $1,$2}' | kill -9

#     - name: wait until the scan_web_port is down
#       wait_for:
#         host: "{{ ansible_host }}"
#         port: "{{ scan_web_port }}"
#         state: stopped
#         msg: "the pump port {{ scan_web_port }} is not down"
