---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/consul"
  - "{{ deploy_dir }}/consul/config"
  - "{{ deploy_dir }}/consul/data-dir"
  - "{{ deploy_dir }}/consul/log"

- name: Set facts
  set_fact:
    data_dir: "{{ deploy_dir }}/consul/data-dir"
    log_file: "{{ deploy_dir }}/consul/log"

- name: "copy configuration file"
  template:
    src: "consul.json.j2"
    dest: "{{ deploy_dir }}/consul/config/consul.json"
    mode: 0600

# - name: "copy consul binary Executable file"
#   copy:
#     src: "{{ downloads_dir }}/consul"
#     dest: "{{ deploy_dir }}/consul/consul"
#     mode: 0775
#     backup: yes

- name: Extract consul zip 
  unarchive:
    src: "{{ downloads_dir }}/ {{ consul_zip_name }}"
    dest: "{{ downloads_dir }}"
    copy: yes
    mode: 0755