---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/via"
  - "{{ deploy_dir }}/via/config"
  - "{{ deploy_dir }}/via/cert"
  - "{{ deploy_dir }}/via/log"

- name: set via_log_file facts
  set_fact:
    via_log_file: "{{ deploy_dir }}/via/log/via.log"

- name: "Copy certificate"
  copy:
    src: "{{ via_cert_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/via/cert/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - ca.pem
    - server.pem
    - server.key
    - client.pem
    - client.key

- name: Set certificate-related facts
  set_fact:
    via_cert_file: "{{ deploy_dir }}/via/cert/server.pem"
    via_key_file: "{{ deploy_dir }}/via/cert/server.key"
    io_cert_file: "{{ deploy_dir }}/via/cert/client.pem"
    io_key_file: "{{ deploy_dir }}/via/cert/client.key"
    ca_cert_file: "{{ deploy_dir }}/via/cert/ca.pem"

- name: "copy configuration file"
  template:
    src: "via.yml.j2"
    dest: "{{ deploy_dir }}/via/config/via.yml"
    mode: 0600

- name: "copy via binary Executable file"
  copy:
    src: "{{ downloads_dir }}/via"
    dest: "{{ deploy_dir }}/via/via"
    mode: 0775
    backup: yes