---

# 判断操作系统
- name: Get distro name from /etc/os-release
  shell: "([ -f /etc/os-release ] && grep '^NAME=' /etc/os-release | sed s'/NAME=//' | tr -d \\\")"
  register: distro_result

- name: Debug distro_result information
  debug:
    var: distro_result.stdout

- name: Check operating system
  fail: msg="Currently, only Ubuntu is supported"
  when: "'Ubuntu' != distro_result.stdout"

# 判断操作系统版本
- name: Get distro_version from /etc/issue
  shell: "cat /etc/issue | head -n 1 | awk '{print $2}' | cut -b 1-5"
  register: distro_version_result

- name: Debug distro_version information
  debug:
    var: distro_version_result.stdout

- name: Check operating system version
  fail: msg="Currently, only Ubuntu 18.04 is supported"
  when: "'18.04' != distro_version_result.stdout"