---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/carrier"
  - "{{ deploy_dir }}/carrier/config"
  - "{{ deploy_dir }}/carrier/cert"
  - "{{ deploy_dir }}/carrier/p2p_priv_key"
  - "{{ deploy_dir }}/carrier/datadir"

- name: set carrier_data_dir facts
  set_fact:
    carrier_data_dir: "{{ deploy_dir }}/carrier/datadir"

- name: "Deploy certificates"
  copy:
    src: "{{ carrier_cert_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/carrier/cert/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - server.pem 
    - server.key

- name: Set certificate-related facts
  set_fact:
    carrier_tls_cert: "{{ deploy_dir }}/carrier/cert/server.pem"
    carrier_tls_key: "{{ deploy_dir }}/carrier/cert/server.key"

- name: "copy keytool binary Executable file"
  copy:
    src: "{{ downloads_dir }}/keytool"
    dest: "{{ deploy_dir }}/carrier/keytool"
    mode: 0775
    backup: yes

- name: "Generate p2p private key file"
  shell: "{{ deploy_dir }}/carrier/keytool genkeypair | head -n 1 | awk -v FS=' ' '{print $2}' > {{ deploy_dir }}/carrier/p2p_priv_key/p2p_priv_key"

- name: set carrier_p2p_private_key facts
  set_fact:
    carrier_p2p_private_key: "{{ deploy_dir }}/carrier/p2p_priv_key/p2p_priv_key"

- name: "copy configuration file"
  template:
    src: "carrier.yml.j2"
    dest: "{{ deploy_dir }}/carrier/config/carrier.yml"
    mode: 0600
    backup: yes

- name: "copy carrier binary Executable file"
  copy:
    src: "{{ downloads_dir }}/carrier"
    dest: "{{ deploy_dir }}/carrier/carrier"
    mode: 0775
    backup: yes