---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/scan"
  - "{{ deploy_dir }}/scan/config"
  - "{{ deploy_dir }}/scan/cert"
  - "{{ deploy_dir }}/scan/cert/web"
  - "{{ deploy_dir }}/scan/log"
  - "{{ deploy_dir }}/scan/network"

- name: "Deploy certificates"
  copy:
    src: "{{ scan_cert_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/scan/cert/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - server.pem 
    - server.key

- name: "Deploy web certificates"
  copy:
    src: "{{ scan_cert_dir }}/web/{{ item }}"
    dest: "{{ deploy_dir }}/scan/cert/web/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - server.pem 
    - server.key

- name: Set web certificate-related facts
  set_fact:
    scan_ssl_cetificate: "{{ deploy_dir }}/scan/cert/web/server.pem"
    scan_ssl_cetificate_key: "{{ deploy_dir }}/scan/cert/web/server.key"

- name: "copy configuration file"
  template:
    src: "scan.yml.j2"
    dest: "{{ deploy_dir }}/scan/config/scan.yml"
    mode: 0600
    backup: yes

- name: "copy scan jar package"
  copy:
    src: "{{ downloads_dir }}/scan.jar"
    dest: "{{ deploy_dir }}/scan/scan"
    mode: 0775
    backup: yes

# 拷贝 web 静态文件
- name: copy and extract scan.tar.gz
  unarchive:
    src: "{{ downloads_dir }}/scan.tar.gz"
    dest: "{{ deploy_dir }}/scan/network"

- name: set scan_web_static_dir facts
  set_fact:
    scan_web_static_dir: "{{ deploy_dir }}/scan/network"

# 安装 nginx
- name: "install nginx"
  become: true
  apt:
    name: ['nginx']
    state: latest

- name: delete default nginx site
  become: true
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: "copy nginx config file"
  become: true
  template:
    src: "metis-scan.platon.network.conf.j2"
    dest: "/etc/nginx/conf.d/metis-scan.platon.network.conf"
    mode: 0600
    backup: yes

- name: restart nginx
  become: true
  service:
    name: nginx
    state: restarted

# java 环境
- name: apt install openjdk-8-jdk
  become: true
  apt:
    name: openjdk-8-jdk
    state: present