---

- name: create deploy directories
  file: path={{ item }} state=directory mode=0755
  with_items:
  - "{{ deploy_dir }}/compute"
  - "{{ deploy_dir }}/compute/config"
  - "{{ deploy_dir }}/compute/cert"
  - "{{ deploy_dir }}/compute/whl"
  - "{{ deploy_dir }}/compute/contract_work_dir"
  - "{{ deploy_dir }}/compute/result_root"

- name: set directory facts
  set_fact:
    code_root_dir: "{{ deploy_dir }}/compute/contract_work_dir"
    results_root_dir: "{{ deploy_dir }}/compute/result_root"

- name: "Deploy certificates"
  copy:
    src: "{{ compute_cert_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/compute/cert/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - server.pem 
    - server.key

- name: Set certificate-related facts
  set_fact:
    base_path: "{{ deploy_dir }}/compute/cert/"

- name: "copy configuration file"
  template:
    src: "compute.yml.j2"
    dest: "{{ deploy_dir }}/compute/config/compute.yml"
    mode: 0600
    backup: yes

# copy Miniconda3-latest-Linux-x86_64.sh
- name: "copy Miniconda3 Executable file"
  copy:
    src: "{{ downloads_dir }}/Miniconda3-latest-Linux-x86_64.sh"
    dest: "{{ deploy_dir }}/miniconda.sh"
    mode: 0755
    backup: yes

# install conda
- name: Install conda
  shell : "([ ! -e {{deploy_dir}}/miniconda ] && ({{deploy_dir}}/miniconda.sh -b -p {{deploy_dir}}/miniconda && {{deploy_dir}}/miniconda/bin/conda init $(echo $SHELL | awk -F '/' '{print $NF}')))|cat"

# install python3.7.5
- name: Install python3.7
  shell: "([ ! -e {{deploy_dir}}/miniconda/envs/python375 ] && ({{deploy_dir}}/miniconda/bin/conda create --name python375 python=3.7.5 -y))|cat"

# copy whl file
- name: "copy whl file"
  copy:
    src: "{{ downloads_dir }}/{{ item }}"
    dest: "{{ deploy_dir }}/compute/whl/{{ item }}"
    mode: 0600
    backup: yes
  with_items:
    - latticex_rosetta-1.0.0-cp37-cp37m-linux_x86_64.whl
    - channel_sdk-2.0.0-cp37-cp37m-linux_x86_64.whl
    - metis_dcv-0.9.1-py3-none-any.whl

# install whl file
- name: "install whl file"
  become: true
  shell : "{{deploy_dir}}/miniconda/envs/python375/bin/python -m pip uninstall channel-sdk metis-dcv latticex-rosetta -y && {{deploy_dir}}/miniconda/envs/python375/bin/python -m pip install {{ deploy_dir }}/data/whl/*.whl -i https://pypi.douban.com/simple/"

# copy start.sh file
- name: "copy start.sh file"
  copy:
    src: "{{ downloads_dir }}/start_v3_service.sh"
    dest: "{{ deploy_dir }}/compute/start_v3_service.sh"
    mode: 0755
    backup: yes